Fix the bug causing Zeppelin notebook installation/start failure
- 'timeout' argument should be urlopen() but not json.load.

The error message solved:

  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/ZEPPELIN/package/scripts/master.py", line 196, in update_zeppelin_interpreter
    data = json.load(urllib2.urlopen(zeppelin_int_url), timeout=60)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'timeout'